version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: ${image}
    ## start automatically
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${defaultUser}
      MONGO_INITDB_ROOT_PASSWORD: ${defaultPassword}
    ports:
      ## default port can be changed by .env
      - "${defaultPort}:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db