version: '3.9'

services:
  mssql:
    container_name: mssql
    image: ${image}
    ## start automatically
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${defaultPassword}
      - MSSQL_DB_NAME
      - MSSQL_SA_PASSWORD
    ports:
      ## default port can be changed by .env
      - "${defaultPort}:1433"
    volumes:
      - type: bind
        source: ${dataFolder}
        target: /var/opt/mssql/data